config/routes.rb
Rails.application.routes.draw do
  resources :carts, :defaults => { :format => 'json' }
  resources :products, :defaults => { :format => 'json' }
  devise_for :users, :defaults => { :format => 'json' }, controllers: { sessions: 'user/sessions', registrations: 'user/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    byebug
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    byebug
  end

  # GET /carts/new
  def new
    byebug
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    # byebug
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    byebug
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    byebug
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      byebug
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.permit(:productId, :productName, :productQty, :productPrice, :totalProducts, :cartValue)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :productId %>
    <%= form.number_field :productId %>
  </div>

  <div class="field">
    <%= form.label :productQty %>
    <%= form.number_field :productQty %>
  </div>

  <div class="field">
    <%= form.label :productPrice %>
    <%= form.number_field :productPrice %>
  </div>

  <div class="field">
    <%= form.label :totalProducts %>
    <%= form.number_field :totalProducts %>
  </div>

  <div class="field">
    <%= form.label :cartValue %>
    <%= form.number_field :cartValue %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>Productid</th>
      <th>Productqty</th>
      <th>Productprice</th>
      <th>Totalproducts</th>
      <th>Cartvalue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.productId %></td>
        <td><%= cart.productQty %></td>
        <td><%= cart.productPrice %></td>
        <td><%= cart.totalProducts %></td>
        <td><%= cart.cartValue %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productid:</strong>
  <%= @cart.productId %>
</p>

<p>
  <strong>Productqty:</strong>
  <%= @cart.productQty %>
</p>

<p>
  <strong>Productprice:</strong>
  <%= @cart.productPrice %>
</p>

<p>
  <strong>Totalproducts:</strong>
  <%= @cart.totalProducts %>
</p>

<p>
  <strong>Cartvalue:</strong>
  <%= @cart.cartValue %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>